### ISSUE TITLE
The Tex Files are wrong with \LaTeX and \TeX symbols.

### ISSUE THREAD

**Issue by iphyer** [chenshuo/typeset#12]
Below is the problem report of my Texlive in Linux:

line 4: Undefined control sequence ...易地把知识应用到 \LaTeX排版中去
line 15: Undefined control sequence ...来排版自己书的人少走一些弯路
line 17: Undefined control sequence ...\LaTeX使用方面的问题请先阅读FAQ
line 29: Undefined control sequence \section{为什么要用\LaTeX排版？}
line 29: Undefined control sequence \section{为什么要用\LaTeX排版？}
line 29: Undefined control sequence \section{为什么要用\LaTeX排版？}
line 29: Undefined control sequence \section{为什么要用\LaTeX排版？}
line 47: Undefined control sequence ...的断行和断页采用动态规划算法
line 61: Undefined control sequence ...和\LaTeX都会把长单词移到第三行
line 101: Undefined control sequence 注意，\TeX本身是非常稳定的
line 156: Undefined control sequence 编辑往往既不会\LaTeX也不会Git
line 96: Undefined control sequence \LaTeX默认是按章重置脚注编号
line 104: Undefined control sequence \LaTeX默认的脚注编号是数字
line 109: Undefined control sequence ...eX默认的脚注位置不是固定置底
: Command \@makecol has changed.
line 38: Token not allowed in a PDF string (Unicode):(hyperref) \kern 1.66672pt(hyperref) removed
: No file typeset.ind.

Actually the problem is caused by \LaTeX and there should be a space behind the \LaTeX command,
And Now there will be only some warnings but no errors and I get the PDF file at last.

: Command \@makecol has changed.
line 38: Token not allowed in a PDF string (Unicode):(hyperref) \kern 1.66672pt(hyperref) removed
: No file typeset.ind.

**Comment by iphyer** [comment]
![Uploading 1.png . . .]()


This is the final result.

**Comment by iphyer** [comment]
The reason is that \LaTeX actually is \LaTeX{} so space is needed for latex to judge just like this webpage has said.

[Space after LaTeX commands](http://tex.stackexchange.com/questions/31091/space-after-latex-commands)

**Comment by chenshuo** [comment]
Which version of TeXLive ?
What command did you run ?

**Comment by iphyer** [comment]
This is XeTeX, Version 3.14159265-2.6-0.99991 (TeX Live 2014) (preloaded format=xelatex)
 restricted \write18 enabled.

Run in TexStudio command is :xelatex -synctex=1 -interaction=nonstopmode %.tex

So I clicked SPACE BAR to  add  space behind the \LaTeX and \TeX and all the compiling and output is OK.

**Comment by chenshuo** [comment]
Fixed.

**Comment by iphyer** [comment]
OK! So quick and wonderful!
