### ISSUE TITLE
Undefined control sequence

### ISSUE THREAD

**Issue by Eagles2F** [chenshuo/typeset#13]
```
[1] <use  "diagrams/linebreak-crop.pdf"  page2>
! Undefined control sequence.
\f@ncyelf ->\small \normalfont \youyuan 
                                        \BookTitle by 陈硕\strut 
l.94 

```

**Comment by Eagles2F** [comment]
Environment: Mac OS,MacTex 2015, all packages updated with Text Live.

**Comment by chenshuo** [comment]
You can use a different font.

**Comment by Eagles2F** [comment]
@chenshuo hi shuo, what do you mean by font? What I saw from the error message looks like a weird fancyhdr problem. Thanks!

**Comment by chenshuo** [comment]
I don't have a Mac, can you reproduce it on Linux ?
